spring:
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:audsatdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  environment:
    TZ: "UTC"
  jpa:
    show-sql: true
    open-in-view: false
